# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'hero_es' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hero.es
  pod 'Firebase/Core', '~> 7.3'
  pod 'Firebase/Auth', '~> 7.3'
  pod 'Firebase/Firestore', '~> 7.3'
  pod 'Alamofire', '~> 5.4'
  pod 'Kingfisher', '~> 5.15'
  pod 'SwiftyJSON', '~> 5.0'

  target 'hero_esTests' do
    inherit! :search_paths
  end
end
