# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'hero.es' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hero.es
  
 
  # Firebase Core
  pod 'Firebase/Core'

  # Firebase Auth
  pod 'Firebase/Auth'

  # Firebase Firestore
  pod 'Firebase/Firestore'
  
  target 'hero.esTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'hero.esUITests' do
    # Pods for testing
  end

end
